### ISSUE TITLE
Version 0.4 cannot be compiled, and version 0.3 has input focus issues

### ISSUE THREAD

**Issue by t1000ln** [fltk-rs/fltk-webview#21]
When using version 0.4 in cargo. toml, RustRover will prompt "Use of an undeclared type ` Webview ` [E0433]".

When using version 0.3, if a webview window is nested in the main window, the input box in the main window will lose focus when the webview page is opened, and no matter how you click on the input box in the main window with the mouse, you cannot input any characters. At the same time, the input characters will always appear on the webview page. Is there a way to regain input focus?

cargo.toml:
```toml
[dependencies]
fltk = { version = "1.4", features = ["use-ninja"]}
fltk-webview = "0.4"
```
